-- ============================================================
-- GDprint v8.0.2 — canonical order creation actions
-- Run AFTER 046_yerevan_time_workday_close.sql
--
-- Fixes: "Customer orders can only be changed through approved GDprint actions"
-- across Website, Manager and Customer App while preserving customer write guards.
-- ============================================================

-- 1) Customer-order guard: staff role always wins over an accidental customer link.
--    Customer INSERTs are accepted only for their own customer row or through a
--    GDprint-approved transaction marker. Customer UPDATE/DELETE remains blocked.
create or replace function public.guard_customer_order_write()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_customer_id uuid;
  v_role text;
  v_approved boolean := false;
begin
  select p.role into v_role
  from public.profiles p
  where p.id=auth.uid()
    and coalesce(p.approval_status,'approved')='approved'
    and coalesce(p.account_status,'active')='active'
  limit 1;

  -- Admin/Manager/Staff writes are governed by their own RLS + role-specific guards.
  if v_role is not null then
    if tg_op='DELETE' then return old; else return new; end if;
  end if;

  v_customer_id := public.current_customer_id();
  v_approved :=
    coalesce(current_setting('app.customer_order_rpc',true),'')='1'
    or coalesce(current_setting('app.gd_order_action',true),'')='1';

  if v_customer_id is not null then
    if v_approved then
      if tg_op='DELETE' then return old; else return new; end if;
    end if;

    -- INSERT of a new order for the signed-in customer's own CRM row is safe at
    -- trigger level; table RLS still decides whether a direct browser INSERT is allowed.
    if tg_op='INSERT'
       and new.customer_id=v_customer_id
       and coalesce(new.created_by_type,'customer')='customer'
       and coalesce(new.source_channel,'website') in ('website','customer_app') then
      return new;
    end if;

    raise exception 'Customer orders can only be changed through approved GDprint actions';
  end if;

  if tg_op='DELETE' then return old; else return new; end if;
end $$;

-- Keep one canonical trigger in place.
drop trigger if exists trg_guard_customer_order_write on public.orders;
create trigger trg_guard_customer_order_write
before insert or update or delete on public.orders
for each row execute function public.guard_customer_order_write();

-- 2) One approved RPC for Website + Manager order creation.
--    The visible order number generated by the page is preserved when valid/unique.
create or replace function public.create_gd_order(
  p_service_key text,
  p_details jsonb,
  p_description text,
  p_full_name text,
  p_phone text,
  p_email text,
  p_language text,
  p_client_total numeric,
  p_requested_channel text,
  p_order_number text default null
)
returns table(id uuid,order_number text,total_amount numeric,status text,service_name text)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_role text;
  v_customer_id uuid;
  v_order public.orders%rowtype;
  v_amount numeric := greatest(coalesce(p_client_total,0),0);
  v_no text;
  v_prefix text;
  v_channel text := lower(trim(coalesce(p_requested_channel,'website')));
  v_lang text := lower(trim(coalesce(p_language,'hy')));
  v_name text := trim(coalesce(p_full_name,''));
  v_phone text := trim(coalesce(p_phone,''));
  v_email text := lower(trim(coalesce(p_email,'')));
  v_details jsonb := coalesce(p_details,'{}'::jsonb);
begin
  if p_service_key not in (
    'wide_format','plotter_cutting','business_cards','photo_printing','rollup','canvas',
    'poster_placement','cup_printing','kinder_box_printing','tshirt_printing','x_banner','self_adhesive_sticker',
    'plotter_file_design','mug_design','business_card_design','banner_design','outdoor_ad_design',
    'rollup_design','corporate_identity','logo_design'
  ) then
    raise exception 'Unknown or retired service';
  end if;

  if v_name='' then raise exception 'Full name is required'; end if;
  if v_phone='' then raise exception 'Phone is required'; end if;
  if v_lang not in ('hy','ru','en') then v_lang:='hy'; end if;
  if v_channel not in ('website','manager') then v_channel:='website'; end if;

  select p.role into v_role
  from public.profiles p
  where p.id=auth.uid()
    and coalesce(p.approval_status,'approved')='approved'
    and coalesce(p.account_status,'active')='active'
  limit 1;

  if v_channel='manager' then
    if coalesce(v_role,'')<>'manager' then raise exception 'Manager access required'; end if;
    if exists(
      select 1 from public.manager_permissions mp
      where mp.manager_id=auth.uid() and coalesce(mp.can_create_orders,true)=false
    ) then
      raise exception 'Order creation is disabled for this manager';
    end if;
  end if;

  -- If a Customer App user orders from the public website in the same browser,
  -- keep the order linked to that customer. Manager orders create/reuse the CRM
  -- customer by the entered customer phone/email instead.
  if v_channel='website' and v_role is null then
    v_customer_id := public.current_customer_id();
  end if;
  if v_customer_id is null then
    v_customer_id := public.get_or_create_customer(v_name,v_phone,nullif(v_email,''));
  end if;

  v_prefix:=case p_service_key
    when 'wide_format' then 'LTP'
    when 'plotter_cutting' then 'PLT'
    when 'business_cards' then 'BC'
    when 'photo_printing' then 'PH'
    when 'rollup' then 'RL'
    when 'canvas' then 'CNV'
    when 'poster_placement' then 'POST'
    when 'cup_printing' then 'CUP'
    when 'kinder_box_printing' then 'KIN'
    when 'tshirt_printing' then 'TSH'
    when 'x_banner' then 'XBN'
    when 'self_adhesive_sticker' then 'STK'
    when 'plotter_file_design' then 'PFD'
    when 'mug_design' then 'MGD'
    when 'business_card_design' then 'BCD'
    when 'banner_design' then 'BND'
    when 'outdoor_ad_design' then 'OAD'
    when 'rollup_design' then 'RUD'
    when 'corporate_identity' then 'CID'
    when 'logo_design' then 'LGD'
    else 'GD' end;

  v_no := upper(trim(coalesce(p_order_number,'')));
  if v_no !~ '^[A-Z0-9]{2,8}-[0-9]{6}$'
     or exists(select 1 from public.orders o where o.order_number=v_no) then
    loop
      v_no:=v_prefix||'-'||floor(100000+random()*900000)::int::text;
      exit when not exists(select 1 from public.orders o where o.order_number=v_no);
    end loop;
  end if;

  perform set_config('app.gd_order_action','1',true);

  insert into public.orders(
    order_number,customer_id,customer_name,customer_phone,customer_email,
    created_by_type,created_by_manager_id,source_channel,
    service_key,service_name,language,total_amount,description,status
  ) values (
    v_no,v_customer_id,v_name,v_phone,nullif(v_email,''),
    case when v_channel='manager' then 'manager' else 'customer' end,
    case when v_channel='manager' then auth.uid() else null end,
    v_channel,
    p_service_key,public.gd_service_name(p_service_key),v_lang,v_amount,
    coalesce(p_description,''),'pending'
  ) returning * into v_order;

  insert into public.order_details(order_id,details)
  values(
    v_order.id,
    v_details || jsonb_build_object(
      '_server_price',v_amount,
      '_created_from',v_channel,
      '_created_via','create_gd_order'
    )
  );

  insert into public.order_status_history(order_id,old_status,new_status,changed_by)
  values(v_order.id,null,'pending',case when v_channel='manager' then auth.uid() else null end);

  return query
  select v_order.id,v_order.order_number,v_order.total_amount,v_order.status,v_order.service_name;
end $$;

revoke all on function public.create_gd_order(text,jsonb,text,text,text,text,text,numeric,text,text) from public;
grant execute on function public.create_gd_order(text,jsonb,text,text,text,text,text,numeric,text,text) to anon,authenticated;

-- 3) Customer App RPC: explicit customer_app source + own customer row.
--    Server pricing remains authoritative in the Customer App.
create or replace function public.create_customer_order(
  p_service_key text,
  p_details jsonb,
  p_description text default ''
)
returns table(id uuid,order_number text,total_amount numeric,status text,service_name text)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_customer public.customers%rowtype;
  v_amount numeric;
  v_no text;
  v_order public.orders%rowtype;
  v_prefix text;
begin
  select * into v_customer
  from public.customers
  where auth_user_id=auth.uid()
  limit 1;
  if v_customer.id is null then raise exception 'Customer account not found'; end if;

  if p_service_key not in (
    'wide_format','plotter_cutting','business_cards','photo_printing','rollup','canvas',
    'poster_placement','cup_printing','kinder_box_printing','tshirt_printing','x_banner','self_adhesive_sticker',
    'plotter_file_design','mug_design','business_card_design','banner_design','outdoor_ad_design',
    'rollup_design','corporate_identity','logo_design'
  ) then raise exception 'Unknown or retired service'; end if;

  v_amount:=public.gd_customer_price(p_service_key,coalesce(p_details,'{}'::jsonb));
  v_prefix:=case p_service_key
    when 'wide_format' then 'LTP' when 'plotter_cutting' then 'PLT'
    when 'business_cards' then 'BC' when 'photo_printing' then 'PH'
    when 'rollup' then 'RL' when 'canvas' then 'CNV'
    when 'poster_placement' then 'POST' when 'cup_printing' then 'CUP'
    when 'kinder_box_printing' then 'KIN' when 'tshirt_printing' then 'TSH'
    when 'x_banner' then 'XBN' when 'self_adhesive_sticker' then 'STK'
    when 'plotter_file_design' then 'PFD' when 'mug_design' then 'MGD'
    when 'business_card_design' then 'BCD' when 'banner_design' then 'BND'
    when 'outdoor_ad_design' then 'OAD' when 'rollup_design' then 'RUD'
    when 'corporate_identity' then 'CID' when 'logo_design' then 'LGD'
    else 'GD' end;

  loop
    v_no:=v_prefix||'-'||floor(100000+random()*900000)::int::text;
    exit when not exists(select 1 from public.orders o where o.order_number=v_no);
  end loop;

  perform set_config('app.customer_order_rpc','1',true);
  perform set_config('app.gd_order_action','1',true);

  insert into public.orders(
    order_number,customer_id,customer_name,customer_phone,customer_email,
    created_by_type,created_by_manager_id,source_channel,
    service_key,service_name,language,total_amount,description,status
  ) values (
    v_no,v_customer.id,v_customer.full_name,v_customer.phone,v_customer.email,
    'customer',null,'customer_app',
    p_service_key,public.gd_service_name(p_service_key),'hy',v_amount,
    coalesce(p_description,''),'pending'
  ) returning * into v_order;

  insert into public.order_details(order_id,details)
  values(
    v_order.id,
    coalesce(p_details,'{}'::jsonb)||jsonb_build_object(
      '_server_price',v_amount,
      '_created_from','customer_app',
      '_created_via','create_customer_order'
    )
  );

  insert into public.order_status_history(order_id,old_status,new_status,changed_by)
  values(v_order.id,null,'pending',null);

  insert into public.customer_app_notifications(customer_id,order_id,type,title,message)
  values(v_customer.id,v_order.id,'order_created','Պատվերն ընդունված է','Ձեր '||v_no||' պատվերը հաջողությամբ գրանցվել է։');

  return query
  select v_order.id,v_order.order_number,v_order.total_amount,v_order.status,v_order.service_name;
end $$;

revoke all on function public.create_customer_order(text,jsonb,text) from public;
grant execute on function public.create_customer_order(text,jsonb,text) to authenticated;

-- 4) Website/Manager file upload: allow recent website orders and the manager's
--    own recent manager orders in website/<order-number>/... storage paths.
create or replace function public.can_upload_website_order_file(p_object_name text)
returns boolean
language sql
stable
security definer
set search_path=public,storage
as $$
  select
    (storage.foldername(p_object_name))[1]='website'
    and coalesce((storage.foldername(p_object_name))[2],'')<>''
    and exists(
      select 1
      from public.orders o
      where o.order_number=(storage.foldername(p_object_name))[2]
        and o.created_at>now()-interval '2 hours'
        and (
          coalesce(o.created_by_type,'customer')='customer'
          or (
            o.created_by_type='manager'
            and o.created_by_manager_id=auth.uid()
            and exists(
              select 1 from public.profiles p
              where p.id=auth.uid() and p.role='manager'
                and coalesce(p.approval_status,'approved')='approved'
                and coalesce(p.account_status,'active')='active'
            )
          )
        )
    );
$$;
revoke all on function public.can_upload_website_order_file(text) from public;
grant execute on function public.can_upload_website_order_file(text) to anon,authenticated;

drop policy if exists website_anon_upload_order_files on storage.objects;
drop policy if exists website_upload_order_files on storage.objects;
create policy website_upload_order_files
on storage.objects
for insert
to anon,authenticated
with check(
  bucket_id='customer-order-files'
  and public.can_upload_website_order_file(name)
);

create or replace function public.attach_website_order_file(
  p_order_id uuid,
  p_order_number text,
  p_file_name text,
  p_storage_path text
)
returns void
language plpgsql
security definer
set search_path=public,storage
as $$
begin
  if p_order_id is null or coalesce(trim(p_order_number),'')='' then
    raise exception 'Invalid order';
  end if;
  if p_storage_path is null or p_storage_path not like ('website/'||p_order_number||'/%') then
    raise exception 'Invalid storage path';
  end if;
  if not exists(
    select 1 from public.orders o
    where o.id=p_order_id
      and o.order_number=p_order_number
      and o.created_at>now()-interval '2 hours'
      and (
        coalesce(o.created_by_type,'customer')='customer'
        or (o.created_by_type='manager' and o.created_by_manager_id=auth.uid())
      )
  ) then
    raise exception 'Order is not eligible for website file attachment';
  end if;
  if not exists(
    select 1 from storage.objects s
    where s.bucket_id='customer-order-files' and s.name=p_storage_path
  ) then
    raise exception 'Uploaded object was not found';
  end if;

  insert into public.order_files(order_id,file_name,storage_path)
  values(p_order_id,left(coalesce(p_file_name,'file'),500),p_storage_path);
end $$;
revoke all on function public.attach_website_order_file(uuid,text,text,text) from public;
grant execute on function public.attach_website_order_file(uuid,text,text,text) to anon,authenticated;

-- 5) Quick diagnostic.
create or replace function public.gd_order_creation_health()
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
select jsonb_build_object(
  'version','8.0.2',
  'create_gd_order_ready',to_regprocedure('public.create_gd_order(text,jsonb,text,text,text,text,text,numeric,text,text)') is not null,
  'create_customer_order_ready',to_regprocedure('public.create_customer_order(text,jsonb,text)') is not null,
  'guard_trigger_ready',exists(select 1 from pg_trigger where tgname='trg_guard_customer_order_write' and not tgisinternal),
  'checked_at',now()
);$$;
revoke all on function public.gd_order_creation_health() from public;
grant execute on function public.gd_order_creation_health() to anon,authenticated;

notify pgrst, 'reload schema';
