let MW_CUSTOMERS=[], MW_ACTIVE=null, MW_USER=null;
(async()=>{const a=await requireRole(['manager']);if(!a)return;MW_USER=a.profile;await Promise.all([loadCustomers(),loadQuotes()]);document.getElementById('mw-search').oninput=renderCustomers;document.getElementById('mw-save-contact').onclick=saveContact;document.getElementById('mw-quote').onsubmit=saveQuote;})();
async function loadCustomers(){const {data,error}=await supabaseClient.from('customers').select('id,full_name,phone,email,orders(id,order_number,service_name,status,created_at)').order('created_at',{ascending:false});if(error){toast(error.message,'error');return;}MW_CUSTOMERS=data||[];document.getElementById('mw-customer').innerHTML='<option value="">— ընտրել —</option>'+MW_CUSTOMERS.map(c=>`<option value="${c.id}">${escapeHtml(c.full_name||c.phone||c.email||c.id)}</option>`).join('');renderCustomers();}
function renderCustomers(){const q=document.getElementById('mw-search').value.toLowerCase();const list=MW_CUSTOMERS.filter(c=>!q||[c.full_name,c.phone,c.email].some(v=>(v||'').toLowerCase().includes(q)));document.getElementById('mw-customers').innerHTML=list.map(c=>`<button class="btn" style="width:100%;justify-content:flex-start;margin-top:8px" onclick="selectCustomer('${c.id}')"><b>${escapeHtml(c.full_name||'—')}</b>&nbsp; · ${escapeHtml(c.phone||c.email||'—')} · ${(c.orders||[]).length} պատվեր</button>`).join('')||'<div class="page-sub">Չկա</div>';}
async function selectCustomer(id){MW_ACTIVE=id;const c=MW_CUSTOMERS.find(x=>x.id===id);document.getElementById('mw-contact-title').textContent=`Կապի պատմություն — ${c?.full_name||'Հաճախորդ'}`;document.getElementById('mw-customer').value=id;await loadContact();}
async function loadContact(){if(!MW_ACTIVE)return;const {data,error}=await supabaseClient.from('customer_crm_notes').select('*').eq('customer_id',MW_ACTIVE).order('created_at',{ascending:false});const el=document.getElementById('mw-contact-history');if(error){el.innerHTML=`<div class="page-sub">${escapeHtml(error.message)}</div>`;return;}el.innerHTML=(data||[]).map(x=>`<div style="padding:9px 0;border-bottom:1px solid var(--border)"><b>${escapeHtml(x.kind)}</b> — ${escapeHtml(x.note)} <small class="page-sub">${formatDate(x.created_at)}</small></div>`).join('')||'<div class="page-sub">Պատմություն չկա</div>';}
async function saveContact(){if(!MW_ACTIVE){toast('Ընտրեք հաճախորդ','error');return;}const note=document.getElementById('mw-contact-note').value.trim();if(!note)return;const {error}=await supabaseClient.from('customer_crm_notes').insert({customer_id:MW_ACTIVE,kind:document.getElementById('mw-kind').value,note,created_by:MW_USER.id});if(error){toast(error.message,'error');return;}document.getElementById('mw-contact-note').value='';toast('Պահպանվեց','success');loadContact();}
async function saveQuote(e){e.preventDefault();const title=document.getElementById('mw-title').value.trim();const {error}=await supabaseClient.from('manager_quote_requests').insert({manager_id:MW_USER.id,customer_id:document.getElementById('mw-customer').value||null,title,requested_amount:Number(document.getElementById('mw-amount').value||0),note:document.getElementById('mw-note').value.trim()});if(error){toast(error.message,'error');return;}e.target.reset();toast('Ուղարկվեց Admin-ի հաստատման','success');loadQuotes();}
async function loadQuotes(){const {data,error}=await supabaseClient.from('manager_quote_requests').select('*').order('created_at',{ascending:false});const el=document.getElementById('mw-quotes');if(error){el.innerHTML='<div class="page-sub">Migration 034-ը գործարկեք</div>';return;}el.innerHTML=(data||[]).map(x=>`<div style="padding:10px 0;border-bottom:1px solid var(--border)"><b>${escapeHtml(x.title)}</b> · ${formatMoney(x.requested_amount)} · <span>${escapeHtml(x.status)}</span>${x.approved_amount!=null?` · հաստատված ${formatMoney(x.approved_amount)}`:''}</div>`).join('')||'<div class="page-sub">Առաջարկներ չկան</div>';}
