const DESIGN_IMAGES_V763={"plotter_file_design": "../../assets/img/services/33-plotter-file-design.png", "mug_design": "../../assets/img/services/34-mug-design.png", "business_card_design": "../../assets/img/services/35-business-card-design.png", "banner_design": "../../assets/img/services/36-banner-design.png", "outdoor_ad_design": "../../assets/img/services/37-outdoor-ad-design.png", "rollup_design": "../../assets/img/services/38-rollup-design.png", "corporate_identity": "../../assets/img/services/39-corporate-identity.png", "logo_design": "../../assets/img/services/40-logo-design.png"};
let DATA=[];let DOM={};
const $=id=>document.getElementById(id);
(async()=>{if(!await requireRole(['admin']))return;DOM={q:$('q'),state:$('state'),rows:$('rows'),newBtn:$('newBtn'),dlg:$('dlg'),form:$('service-form'),closeBtn:$('closeBtn'),cancelBtn:$('cancelBtn'),id:$('id'),code:$('code'),name_hy:$('name_hy'),name_ru:$('name_ru'),name_en:$('name_en'),category:$('category'),base_price:$('base_price'),unit:$('unit'),min_qty:$('min_qty'),website_visible:$('website_visible'),active:$('active')};bind();await load()})();
function openModal(){DOM.dlg.classList.add('open');DOM.dlg.setAttribute('aria-hidden','false');document.body.classList.add('gd-modal-open');setTimeout(()=>DOM.name_hy.focus(),0)}
function closeModal(){DOM.dlg.classList.remove('open');DOM.dlg.setAttribute('aria-hidden','true');document.body.classList.remove('gd-modal-open')}
function bind(){DOM.q.addEventListener('input',render);DOM.state.addEventListener('change',render);DOM.newBtn.addEventListener('click',()=>edit());DOM.closeBtn.addEventListener('click',closeModal);DOM.cancelBtn.addEventListener('click',closeModal);DOM.dlg.addEventListener('click',e=>{if(e.target===DOM.dlg)closeModal()});DOM.form.addEventListener('submit',async e=>{e.preventDefault();await persist()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&DOM.dlg.classList.contains('open'))closeModal()})}
async function load(){DOM.rows.innerHTML='<tr><td colspan="9">Բեռնվում է…</td></tr>';const {data,error}=await supabaseClient.rpc('admin_master_data_list',{p_module:'services'});if(error){DOM.rows.innerHTML=`<tr><td colspan="9">${error.message}<br><small>Գործարկեք 036 migration-ը</small></td></tr>`;return;}DATA=Array.isArray(data)?data:[];render()}
function render(){let a=DATA.filter(x=>!DOM.q.value||`${x.code||''} ${x.name_hy||''} ${x.category||''}`.toLowerCase().includes(DOM.q.value.toLowerCase()));if(DOM.state.value)a=a.filter(x=>DOM.state.value==='active'?x.active:!x.active);DOM.rows.innerHTML=a.map(x=>`<tr><td>${DESIGN_IMAGES_V763[x.code]?`<img src="${DESIGN_IMAGES_V763[x.code]}" alt="" style="width:64px;height:44px;object-fit:cover;border-radius:8px;display:block">`:'—'}</td><td>${x.code||'—'}</td><td><b>${x.name_hy||'—'}</b></td><td>${x.category||'—'}</td><td>${formatMoney(x.base_price)}</td><td>${x.min_qty??1} ${x.unit||''}</td><td>${x.website_visible?'Այո':'Ոչ'}</td><td>${x.active?'Ակտիվ':'Անջատված'}</td><td><button type="button" class="btn btn-sm" data-edit="${x.id}">Խմբագրել</button></td></tr>`).join('')||'<tr><td colspan="9">Տվյալներ չկան</td></tr>';DOM.rows.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>edit(b.dataset.edit)))}
function edit(id){const x=DATA.find(v=>v.id===id)||{};DOM.id.value=x.id||'';DOM.code.value=x.code||'';DOM.name_hy.value=x.name_hy||'';DOM.name_ru.value=x.name_ru||'';DOM.name_en.value=x.name_en||'';DOM.category.value=x.category||'';DOM.base_price.value=x.base_price??0;DOM.unit.value=x.unit||'հատ';DOM.min_qty.value=x.min_qty??1;DOM.active.checked=x.active!==false;DOM.website_visible.checked=x.website_visible!==false;openModal()}
async function persist(){const payload={code:DOM.code.value.trim(),name_hy:DOM.name_hy.value.trim(),name_ru:DOM.name_ru.value.trim(),name_en:DOM.name_en.value.trim(),category:DOM.category.value.trim(),base_price:Number(DOM.base_price.value)||0,unit:DOM.unit.value.trim()||'հատ',min_qty:Number(DOM.min_qty.value)||1,active:DOM.active.checked,website_visible:DOM.website_visible.checked};if(!payload.name_hy)return toast('Անվանումը պարտադիր է','error');const btn=$('save');btn.disabled=true;try{const {error}=await supabaseClient.rpc('admin_master_data_save',{p_module:'services',p_id:DOM.id.value||null,p_payload:payload});if(error)throw error;closeModal();toast('Պահպանված է','success');await load()}catch(e){toast(e.message||'Չհաջողվեց պահպանել','error')}finally{btn.disabled=false}}
