let PROD=[]; const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roleTitles={designer:'Designer / Prepress',digital_print:'Թվային տպագրություն',large_format:'Լայնաֆորմատ / Plotter',finishing:'Հետտպագրական աշխատանք',quality_control:'Quality Control',packing:'Փաթեթավորում'};
function oid(){return document.getElementById('prod-order').value} function checked(id){return document.getElementById(id)?.checked||false} function val(id){return document.getElementById(id)?.value||''}
async function prodBoot(){while(!window.STAFF_AUTH)await new Promise(r=>setTimeout(r,50));const r=STAFF_AUTH.profile.role;if(!roleTitles[r]){location.href='dashboard.html';return}document.getElementById('prod-title').textContent=roleTitles[r]+' · աշխատանքային կենտրոն';const {data,error}=await supabaseClient.rpc('staff_production_snapshot');if(error){document.getElementById('role-workspace').textContent=error.message;return}PROD=data.orders||[];document.getElementById('prod-order').innerHTML=PROD.map(x=>`<option value="${x.order_id}">${esc(x.order_number)} · ${esc(x.service_name||x.service_key||'')}</option>`).join('')||'<option value="">Նշանակված պատվեր չկա</option>';document.getElementById('prod-queue').innerHTML=PROD.map(x=>`<div class="task"><div class="task-top"><div><b>${esc(x.order_number)}</b><div class="staff-muted">${esc(x.service_name||x.service_key||'')} · ${esc(x.stage||'')}</div></div><span class="badge">${esc(x.priority||'normal')}</span></div><div class="task-meta"><span class="badge">${esc(x.status)}</span>${x.deadline?`<span class="badge">Deadline: ${gdFormatDateTime(x.deadline)}</span>`:''}</div></div>`).join('')||'<div class="staff-muted">Հերթը դատարկ է։</div>';renderRole(r)}
function commonActions(extra=''){return `<div class="staff-card"><h2 style="margin-top:0;font-size:17px">Արտադրական գործողություն</h2><div class="field-row"><div class="field"><label>Կատարված քանակ</label><input id="pqty" type="number" min="0"></div><div class="field"><label>Խոտան / waste</label><input id="pwaste" type="number" min="0"></div><div class="field"><label>Նյութ</label><input id="pmaterial"></div></div><div class="field"><label>Նշում</label><textarea id="pnote"></textarea></div><div class="task-actions"><button class="btn btn-primary" onclick="prodAction('start')">Սկսել</button><button class="btn btn-ghost" onclick="prodAction('pause')">Դադար</button>${extra}</div></div>`}
function renderRole(r){let html='';if(r==='designer')html=`<div class="staff-card"><h2 style="margin-top:0;font-size:17px">Preflight checklist</h2>${['size:Չափս','bleed:Bleed','cmyk:CMYK','resolution:Resolution','fonts:Fonts','cut:Cut contour'].map(x=>{let [i,l]=x.split(':');return `<label style="display:block;margin:8px 0"><input id="pf-${i}" type="checkbox"> ${l}</label>`}).join('')}<div class="field"><label>Նշում</label><textarea id="pf-note"></textarea></div><button class="btn btn-primary" onclick="savePreflight()">Պահպանել ստուգումը</button><a class="btn btn-ghost" href="files.html">Preview / Final file</a></div>`;
if(r==='digital_print')html=commonActions(`<button class="btn btn-ghost" onclick="prodAction('printed')">Տպագրված</button><button class="btn btn-ghost" onclick="prodAction('reprint')">Վերատպում</button><button class="btn btn-ghost" onclick="prodAction('defect')">Խոտան</button><button class="btn btn-primary" onclick="prodAction('completed')">Ուղարկել հաջորդ փուլ</button>`)+equipment();
if(r==='large_format')html=commonActions(`<button class="btn btn-ghost" onclick="prodAction('printed')">Տպագրվել է</button><button class="btn btn-ghost" onclick="prodAction('cut')">Կտրվել է</button><button class="btn btn-ghost" onclick="prodAction('laminated')">Լամինացված է</button><button class="btn btn-ghost" onclick="prodAction('defect')">Խոտան</button><button class="btn btn-primary" onclick="prodAction('completed')">Ուղարկել finishing</button>`)+equipment();
if(r==='finishing')html=commonActions(`<select id="finish-action"><option value="cutting">Կտրում</option><option value="lamination">Լամինացիա</option><option value="folding">Ծալում</option><option value="creasing">Բիգովկա</option><option value="stitching">Կարում</option><option value="gluing">Սոսնձում</option><option value="perforation">Պերֆորացիա</option><option value="packing">Փաթեթավորում</option></select><button class="btn btn-ghost" onclick="prodAction(val('finish-action'))">Գրանցել գործողությունը</button><button class="btn btn-primary" onclick="prodAction('completed')">Ավարտել → հաջորդ փուլ</button>`);
if(r==='quality_control')html=`<div class="staff-card"><h2 style="margin-top:0;font-size:17px">Որակի ստուգում</h2>${['q-qty:Քանակ','q-size:Չափս','q-color:Գույն','q-fin:Finishing'].map(x=>{let [i,l]=x.split(':');return `<label style="display:block;margin:8px 0"><input id="${i}" type="checkbox"> ${l}՝ համապատասխանում է</label>`}).join('')}<div class="field-row"><div class="field"><label>Արդյունք</label><select id="q-result"><option value="approved">Ընդունել → Packing</option><option value="rework">Վերադարձնել վերամշակման</option></select></div><div class="field"><label>Վերադարձի փուլ</label><select id="q-stage"><option value="prepress">Designer / Prepress</option><option value="digital_print">Digital Print</option><option value="large_format">Large Format</option><option value="finishing">Finishing</option></select></div><div class="field"><label>Խոտանի քանակ</label><input id="q-defect" type="number" min="0"></div></div><div class="field"><label>Պատճառ / նշում</label><textarea id="q-reason"></textarea></div><button class="btn btn-primary" onclick="saveQC()">Գրանցել QC արդյունքը</button></div>`;
if(r==='packing')html=`<div class="staff-card"><h2 style="margin-top:0;font-size:17px">Փաթեթավորման հաստատում</h2><label style="display:block;margin:8px 0"><input id="pk-qty" type="checkbox"> Քանակը ստուգված է</label><label style="display:block;margin:8px 0"><input id="pk-quality" type="checkbox"> Որակը ստուգված է</label><label style="display:block;margin:8px 0"><input id="pk-packed" type="checkbox"> Փաթեթավորված է</label><label style="display:block;margin:8px 0"><input id="pk-ready" type="checkbox"> Պատրաստ է առաքման / Pickup</label><div class="field-row"><div class="field"><label>Փաթեթների քանակ</label><input id="pk-count" type="number" min="1"></div><div class="field"><label>Label / QR / Order ID</label><input id="pk-label"></div></div><div class="field"><label>Հատուկ նշումներ</label><textarea id="pk-note"></textarea></div><button class="btn btn-primary" onclick="savePacking()">Հաստատել փաթեթավորումը</button></div>`;document.getElementById('role-workspace').innerHTML=html}
function equipment(){return `<div class="staff-card" style="margin-top:16px"><h2 style="margin-top:0;font-size:17px">Սարքավորման վիճակ</h2><div class="field-row"><div class="field"><label>Տեսակ</label><select id="eq-type"><option value="problem">Սարքի խնդիր</option><option value="maintenance">Սպասարկման պահանջ</option><option value="downtime">Սարքի կանգ</option></select></div><div class="field"><label>Սարք</label><input id="eq-name"></div></div><div class="field"><label>Նկարագրություն</label><textarea id="eq-note"></textarea></div><button class="btn btn-ghost" onclick="reportEquipment()">Գրանցել խնդիրը</button></div>`}
async function call(name,args,msg){if(!oid())return alert('Ընտրեք պատվերը');const {error}=await supabaseClient.rpc(name,args);if(error)return alert(error.message);toast?.(msg,'success');await prodBoot()}
async function prodAction(a){await call('staff_record_production_action',{p_order_id:oid(),p_action:a,p_quantity:Number(val('pqty'))||null,p_waste:Number(val('pwaste'))||null,p_material:val('pmaterial')||null,p_note:val('pnote')||null},'Գործողությունը գրանցվեց')}
async function savePreflight(){await call('staff_save_preflight',{p_order_id:oid(),p_size:checked('pf-size'),p_bleed:checked('pf-bleed'),p_cmyk:checked('pf-cmyk'),p_resolution:checked('pf-resolution'),p_fonts:checked('pf-fonts'),p_cut:checked('pf-cut'),p_note:val('pf-note')||null},'Preflight-ը պահպանվեց')}
async function saveQC(){await call('staff_save_quality_check',{p_order_id:oid(),p_quantity:checked('q-qty'),p_size:checked('q-size'),p_color:checked('q-color'),p_finishing:checked('q-fin'),p_result:val('q-result'),p_return_stage:val('q-stage'),p_defect:Number(val('q-defect'))||null,p_reason:val('q-reason')||null},'QC արդյունքը գրանցվեց')}
async function savePacking(){await call('staff_save_packing_check',{p_order_id:oid(),p_quantity:checked('pk-qty'),p_quality:checked('pk-quality'),p_packed:checked('pk-packed'),p_ready:checked('pk-ready'),p_packages:Number(val('pk-count'))||null,p_label:val('pk-label')||null,p_note:val('pk-note')||null},'Փաթեթավորումը գրանցվեց')}
async function reportEquipment(){await call('staff_report_equipment_issue',{p_order_id:oid(),p_type:val('eq-type'),p_equipment:val('eq-name')||null,p_note:val('eq-note')},'Սարքավորման խնդիրը գրանցվեց')}
window.prodAction=prodAction;window.savePreflight=savePreflight;window.saveQC=saveQC;window.savePacking=savePacking;window.reportEquipment=reportEquipment;window.val=val;document.addEventListener('DOMContentLoaded',prodBoot);
